# -*- coding: utf-8 -*-
"""Task 2: Feb Internship NLP- Sentiment Analysis using NLP Pipeline & ML Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7E91vuesjxoZSs4MDXQrqlJDbDn9zYJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

import warnings
warnings.filterwarnings('ignore')

columns = ['Tweet_ID', 'Entity', 'Sentiment', 'Text']
try:
    df = pd.read_csv('twitter_training.csv', names=columns)
except FileNotFoundError:
    print("Please upload 'twitter_training.csv' to the Colab files section.")
    df = pd.DataFrame(columns=columns)

print("Dataset Shape:", df.shape)

df.dropna(subset=['Text'], inplace=True)

df = df[df['Sentiment'] != 'Irrelevant']

print("\nClass Distribution:")
print(df['Sentiment'].value_counts())

sns.countplot(x='Sentiment', data=df, palette='viridis')
plt.title('Sentiment Class Distribution')
plt.show()

print("\nSample Data:")
display(df[['Sentiment', 'Text']].head())

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()

    text = re.sub(r"http\S+|www\S+|https\S+", '', text, flags=re.MULTILINE)
    text = re.sub(r'\@\w+|\#', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)

    #Tokenization
    tokens = text.split()

    cleaned_tokens =[lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return " ".join(cleaned_tokens)

print("Preprocessing text...")
df['Clean_Text'] = df['Text'].apply(preprocess_text)

df = df[df['Clean_Text'] != '']

print("\nBefore vs After Preprocessing:")
display(df[['Text', 'Clean_Text']].head())

X_train_raw, X_test_raw, y_train, y_test = train_test_split(df['Clean_Text'], df['Sentiment'], test_size=0.2, random_state=42)

bow_vectorizer = CountVectorizer(max_features=5000)
X_train_bow = bow_vectorizer.fit_transform(X_train_raw)
X_test_bow = bow_vectorizer.transform(X_test_raw)

tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)

print(f"BoW Training Shape: {X_train_bow.shape}")
print(f"TF-IDF Training Shape: {X_train_tfidf.shape}")

results =[]

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Naive Bayes": MultinomialNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42)
}

def train_and_evaluate(models, X_train, X_test, y_train, y_test, feature_type):
    for name, model in models.items():
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred, average='weighted')
        rec = recall_score(y_test, y_pred, average='weighted')
        f1 = f1_score(y_test, y_pred, average='weighted')

        results.append({
            "Model": name,
            "Feature": feature_type,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1-Score": f1
        })

        print(f"--- {name} ({feature_type}) ---")
        print(classification_report(y_test, y_pred))

print("Evaluating Bag of Words (BoW)...\n")
train_and_evaluate(models, X_train_bow, X_test_bow, y_train, y_test, "BoW")

print("\nEvaluating TF-IDF...\n")
train_and_evaluate(models, X_train_tfidf, X_test_tfidf, y_train, y_test, "TF-IDF")

results_df = pd.DataFrame(results)

display(results_df.sort_values(by='Accuracy', ascending=False))

plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='Accuracy', hue='Feature', data=results_df, palette='Set2')
plt.title('Model Accuracy Comparison: BoW vs TF-IDF')
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.show()